// Session
export const SESSION_START = "SESSION_START";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_FAIL = "SESSION_FAIL";
export const SESSION_LOGOUT = "SESSION_LOGOUT";

// PRODUCT
export const PRODUCT_START = "PRODUCT_START";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

// ARCHIVE PRODUCT
export const ARCHIVE_PRODUCT_START = "ARCHIVE_PRODUCT_START";
export const ARCHIVE_PRODUCT_SUCCESS = "ARCHIVE_PRODUCT_SUCCESS";
export const ARCHIVE_PRODUCT_FAIL = "ARCHIVE_PRODUCT_FAIL";

// GET_PRODUCT
export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

// GET_DRAFTS_PRODUCT
export const GET_DRAFTS_START = "GET_DRAFTS_START";
export const GET_DRAFTS_SUCCESS = "GET_DRAFTS_SUCCESS";
export const GET_DRAFTS_FAIL = "GET_DRAFTS_FAIL";

// GET_DETAILARTICLE_PRODUCT
export const GET_DETAILARTICLE_START = "GET_DETAILARTICLE_START";
export const GET_DETAILARTICLE_SUCCESS = "GET_DETAILARTICLE_SUCCESS";
export const GET_DETAILARTICLE_FAIL = "GET_DETAILARTICLE_FAIL";

// Token authentication constants
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// AUTH VERIFY
export const AUTH_VERIFY_START = "AUTH_VERIFY_START";
export const AUTH_VERIFY_SUCCESS = "AUTH_VERIFY_SUCCESS";
export const AUTH_VERIFY_FAIL = "AUTH_VERIFY_FAIL";

// MESSAGES
export const CREATE_MESSAGES_START = "CREATE_MESSAGES_START";
export const CREATE_MESSAGES_SUCCESS = "CREATE_MESSAGES_SUCCESS";

// ERROR
export const CREATE_ERROR_START = "CREATE_ERROR_START";
export const CREATE_ERROR_SUCCESS = "CREATE_ERROR_SUCCESS";

// NETWORK
export const NETWORK = "http://192.168.0.13:5000";
