"""empty message

Revision ID: 944a2ad25abe
Revises: 
Create Date: 2019-12-12 19:31:11.945512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944a2ad25abe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('publish', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_public_id'), 'post', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_public_id'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
