"""empty message

Revision ID: 9ae8b8432281
Revises: 944a2ad25abe
Create Date: 2019-12-16 10:47:03.378522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae8b8432281'
down_revision = '944a2ad25abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_id')
    # ### end Alembic commands ###
